services:
  soom_be_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soom_go_api
    image: soom_be_service:latest
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - .env
    volumes:
      - .env:/app/.env
    networks:
      - shared_net

networks:
  shared_net:
    external: true
