version: '3.8'

services:

  redis:
    image: redis:7-alpine
    container_name: soom_go_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soom_go_api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  redis_data: