server {
    listen 80;
    server_name 103.247.9.233;

    # 1. Routing untuk Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 2. Routing untuk Backend
    location /api/ {
        # Ini akan mengubah /api/v1/health menjadi /v1/health sebelum ke Go
        rewrite ^/api/(.*) /$1 break;
        
        proxy_pass http://api:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}